### ISSUE TITLE
React tour

### ISSUE THREAD

**Issue by murillojorge** [eoscostarica/evodex#152]
Implement react tour to enable a quick tutorial for each main section.

**Comment by murillojorge** [comment]
Let's include a help icon next to the main buttons so users can activate a tour for each main section.
https://app.zeplin.io/project/5ebb4f7439b0687707bf3078/dashboard?seid=5f5131aec92e98873256adcd

![Desktop HD -  Tour help](https://user-images.githubusercontent.com/1179619/92151728-d88f1600-edde-11ea-92b0-23d1fd77b6ec.png)
![Desktop HD -  Tour help modal](https://user-images.githubusercontent.com/1179619/92151743-db8a0680-edde-11ea-9a16-a2e45329d66e.png)

**Comment by xavier506** [comment]
## Welcome
Welcome to evodex – the new decentralized exchange where users decide the pool fees.
## Exchange
 In the Exchange tab, enter a valid amount and use the dropdown menu to select the token you own and want to exchange.  

Now, select the token you wish to receive. We will calculate this amount for you. You can use the reverse icon anytime. 

## Liquidity
You can look up the current exchange fee for each token using the dropdown menu in the Liquidity tab. 


## Vote Fee
 Finally, in the Vote Fee tab, you may vote for the fee you consider to be the fairest for each token. Please, use a percentage with one decimal format. For example: 0.1%.

**Comment by ldrojas** [comment]
**_Icónos de ayuda:_** 

## Exchange (you give)
Enter a valid amount and use the dropdown menu to select the token you own and want to exchange. 

## Exchange (you receive)
Select the token you wish to receive. We will calculate this amount for you. You can use the reverse icon anytime.

## Liquidity (amount)
Here you can look up the current exchange fee for each token using the dropdown menu.

## Vote Fee (vote)
Here you may vote for the fee you consider to be the fairest for each token. Please, use a percentage with one decimal format. For example: 0.1%.
