### ISSUE TITLE
Problem when loading pairs table from main api

### ISSUE THREAD

**Issue by sergioyuhjtman** [eoscostarica/evodex#205]
The app loads an incomplete table when using main API.
A precise diagnosis for this bug is needed.

**Comment by sergioyuhjtman** [comment]
The app loads an incomplete table when using main API.
A precise diagnosis for this bug is needed.

**Comment by PixelNoob** [comment]
This was a rate-limit problem on one of the nodeos api endpoints, should be fixed now.. closing!
