### ISSUE TITLE
Idea: Main screen should be "exchange" directly

### ISSUE THREAD

**Issue by elmato** [eoscostarica/evodex#27]
On mobile (Android) the first screen i see is token listing.
since the token listing is visible at the bottom, I rather put the exchange screen with 1 EOS <=> USD

**Comment by xavier506** [comment]
![image](https://user-images.githubusercontent.com/5632966/89332963-7e6d2a80-d651-11ea-99fc-228f54a1ceef.png)

Should look like this :

![image](https://user-images.githubusercontent.com/5632966/89332992-8cbb4680-d651-11ea-99ea-66acee7eefc6.png)
