### ISSUE TITLE
Design Ricardian Contract Page

### ISSUE THREAD

**Issue by tetogomez** [eoscostarica/evodex#59]
Design for Ricardian contract Page, also, validate if smart contract has Ricardian contract information if not we should be show a friendly message

**Comment by xavier506** [comment]
- sticky buttons to elect contract 
 - padding top
 - margin around version 
 - icon sizes

**Comment by murillojorge** [comment]
@tetogomez I've styled the main elements, could you help me out with the sticky titles?
https://github.com/eoscostarica/evodex/tree/fix/contractPage
