### ISSUE TITLE
Succes tx after action

### ISSUE THREAD

**Issue by PixelNoob** [eoscostarica/evodex#62]
Estaría bueno que aparezca un mensajito de "success, tx ...." luego de que se lleve a cabo alguna acción, de esta forma el usuario sabe que la transacción fue exitosa.

**Comment by adriexnet** [comment]
Actualmente se debería presentar un mensaje como el de la imagen y al hacer click en el txId abrir bloks.io, en tu dispositivo no se muestra el mensaje?

![Screen Shot 2020-08-04 at 13 23 55](https://user-images.githubusercontent.com/5375168/89335962-f2a9cd00-d655-11ea-95e7-32430dcb9a45.png)

**Comment by PixelNoob** [comment]
No lo ví, pero dejame que pruebo de nuevo.. esta excelente así!

**Comment by PixelNoob** [comment]
Ahí lo vi, esta perfecto!
