### ISSUE TITLE
Check Balance to optimize RAM

### ISSUE THREAD

**Issue by xavier506** [eoscostarica/evodex#80]
Issue reported by sergio in order to optimize RAM 

Add action in eosjs as

Sometimes users won't have the token for RAM payments

**Comment by xavier506** [comment]
@adriexnet / @sergioyuhjtman  

Can you please describe this issue further

**Comment by sergioyuhjtman** [comment]
Whenever a user performs an exchange operation to receive a token that she does not previously have, the RAM for the new record will be paid by evolutiondex. The table belongs to the token contract. This is how the standard eosio.token works (the user will pay for the RAM the first time she sends some amount of that token). It is preferrable to avoid this by making the user sign an "open" action from the token contract in these cases, in the same transaction.
